services:
  db:
    image: postgres:14-alpine3.17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_DB=test_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      interval: 30s
      timeout: 30s
      retries: 3
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        options: --reload
    environment:
      - DBURL=postgresql://dbuser:pass123@db/test_db
    command: gunicorn main:app --bind 0.0.0.0:5000
    env_file:
      - ./.env
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: